export default  `
query getcart {
    cart {
      isEmpty
      total
      contents {
        itemCount
        edges {
          node {
            quantity
            key
            product {
              node {
                id
                name
                image {
                  sourceUrl(size: SHOP_THUMBNAIL)
                }
                ... on SimpleProduct {
                  price(format: FORMATTED)
                }
              }
            }
          }
        }
      }
    }
  }
`;